### ISSUE TITLE
Post-0.1.0 actions.

### ISSUE THREAD

**Issue by joshmoore** [openmicroscopy/omero-weberror#8]
* Does the tag need bumping to DEV, SNAPSHOT, or similar?
 * The README & DESCRIPTION should be updated to point out that this is an app that can be installed for testing notification logic.
 * Repo needs renaming, etc.

**Comment by sbesson** [comment]
On item 1, I think there are 2 ways:
- either bump to a dev/snapshot version immediately after release (a la Maven)
- or add a dependency on `yaclifw` (could be further refactored) to manage the versions using tags

**Comment by jburel** [comment]
The same pattern will have to be applied to all web app repo.
Let's discuss next week.

**Comment by aleksandra-tarkowska** [comment]
Regarding version I am guessing we should follow PEP440 https://packaging.python.org/distributing/#standards-compliance-for-interoperability. I am wondering if we should do local build using https://packaging.python.org/distributing/#local-version-identifiers

**Comment by sbesson** [comment]
Regarding PEP440, I think we want to follow semver recommendations at least for the naming scheme across the organization. Adding a local version identifier  matches what we have implemented in yaclifw using `git-describe` or OMERO.

**Comment by jburel** [comment]
Move the versioning discussion to https://trello.com/c/yVOCHOtb/134-app-version-number-strategy
